eureka:
  instance:
    hostname: ${EUREKA.INSTANCE.HOSTNAME}
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA.CLIENT.SERVICE_URL.DEFAULT_ZONE}

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${JWT_ISSUER_URI}