server:
  port: 4000

springdoc:
  swagger-ui:
    path: /swagger-ui.html

spring:
  application:
    name: api-gateway
  threads:
    virtual:
      enabled: true
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              lower-case-service-id: true
              enabled: true

resilience4j:
  retry:
    configs:
      default:
        max-attempts: 5
        wait-duration: 3s
  circuitbreaker:
    configs:
      default:
        failure-rate-threshold: 50
        sliding-window-type: COUNT_BASED
        sliding-window-size: 10
        register-health-indicator: true
        automatic-transition-from-open-to-half-open-enabled: true
        wait-duration-in-open-state: 5000ms
        minimum-number-of-calls: 5
        permitted-number-of-calls-in-half-open-state: 4
  timelimiter:
    configs:
      default:
        timeout-duration: 3s

management:
  endpoints:
    web:
      exposure:
        include: prometheus